<?php
/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [ 
'Login' => 'Iniciar Sesión',
'Logout' => 'Salir',
'Username...' => 'Nombre de Usuario...',
'Password...' => 'Contraseña...',
'Select Company' => 'Seleccionar Empresa',
'Profile' => 'Perfil',
'Hello' => 'Hola',
'The requested page does not exist.' => 'La página solicitada no existe.',
'Accept' => 'Aceptar',
'No access to companies or not created' => 'No tiene acceso a las empresas o no existen',
'Error' => 'Error',
'Danger' => 'Peligro',
'Success' => 'Exitoso',
'Info' => 'Información',
'Warning' => 'Atención',
'All companies' => 'Todas las empresas'
];
