<?php

/**
 * Message translations.
 *
 * This file is automatically generated by 'yii message' command.
 * It contains the localizable messages extracted from source code.
 * You may modify this file by translating the extracted messages.
 *
 * Each array element represents the translation (value) of a message (key).
 * If the value is empty, the message is considered as not translated.
 * Messages that no longer need translation will have their translations
 * enclosed between a pair of '@@' marks.
 *
 * Message string can be used with plural forms format. Check i18n section
 * of the guide for details.
 *
 * NOTE: this file must be saved in UTF-8 encoding.
 */
return [
    'View'=>'Ver',
    'Update'=>'Actualizar',
    'Delete'=>'Eliminar',
    'Are you sure to delete this item?'=>'¿Desea eliminar este registro?',
    'Actions'=>'Acciones',
    'HTML' => 'HTML',
    'CSV' => 'CSV',
    'Text' => 'Texto',
    'Excel' => 'Excel',
    'Save as HTML' => 'Guardar como HTML',
    'Save as CSV' => 'Guardar como CSV',
    'Save as Text' => 'Guardar como Texto',
    'Save as Excel' => 'Guardar como Excel',
    'Active' => 'Activo',
    'Inactive' => 'Inactivo',
    'Export' => 'Exportar',
    'ExportWorksheet' => 'Exportar Hoja',
    'Export Page Data'=>'Exportar Página',
    'export' => 'exportar',
    'grid-export' => '',
    'The HTML export file will be generated for download.' => 'El archivo HTML será exportado para su descarga',
    'The CSV export file will be generated for download.' => 'El archivo CSV será exportado para su descarga',
    'The TEXT export file will be generated for download.' => 'El archivo de Texto será exportado para su descarga',
    'The EXCEL export file will be generated for download.' => 'El archivo de Excel será exportado para su descarga',
    'Disable any popup blockers in your browser to ensure proper download.' => 'Deshabilitar su bloqueador de PopUps para la correcta descarga',
    'No data found' => 'No se encontraron registros',
    // Demo data
    'Library' => 'Biblioteca',
    'Book Listing' => 'Listado de Libros',
    'Add Book' => 'Nuevo Libro',
    'Reset Grid' => 'Reiniciar Grid',
    'Download Selected' => 'Descargar selección',
    'The table header sticks to the top in this demo as you scroll' => '',
    'The page summary displays SUM for first 3 amount columns and AVG for the last.' => ''
];
